### ISSUE TITLE
compling stormpy with Stable branch of Storm, missing storm/utility/DirectEncodingExporter.h 

### ISSUE THREAD

**Issue by xhajnal** [stormchecker/stormpy#24]
following instructions here: https://moves-rwth.github.io/stormpy/installation.html

Result in missing `storm/utility/DirectEncodingExporter.h`:
```

Step 5 obtain stormpy - (https://moves-rwth.github.io/stormpy/installation.html#installation)
	## as we use stable version of Storm we use stormpy 1.6.0
	$ git clone https://github.com/moves-rwth/stormpy.git --branch 1.6.0
	$ cd stormpy
	$ git branch
	* (no branch)
	$ python3 setup.py develop
	/home/matej/Git/stormpy/src/core/core.cpp:3:50: fatal error: storm/utility/DirectEncodingExporter.h: No such file or directory
	 #include "storm/utility/DirectEncodingExporter.h"
	                                                  ^
	compilation terminated.
	CMakeFiles/core.dir/build.make:120: recipe for target 'CMakeFiles/core.dir/src/core/core.cpp.o' failed
	make[3]: *** [CMakeFiles/core.dir/src/core/core.cpp.o] Error 1
	make[3]: *** Waiting for unfinished jobs....
	CMakeFiles/Makefile2:346: recipe for target 'CMakeFiles/core.dir/all' failed
	make[2]: *** [CMakeFiles/core.dir/all] Error 2
	CMakeFiles/Makefile2:353: recipe for target 'CMakeFiles/core.dir/rule' failed
	make[1]: *** [CMakeFiles/core.dir/rule] Error 2
	Makefile:241: recipe for target 'core' failed
	make: *** [core] Error 2
	Traceback (most recent call last):
	  File "setup.py", line 236, in <module>
	    setup(
	  File "/home/matej/anaconda3/envs/py38/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
	    return distutils.core.setup(**attrs)
	  File "/home/matej/anaconda3/envs/py38/lib/python3.8/distutils/core.py", line 148, in setup
	    dist.run_commands()
	  File "/home/matej/anaconda3/envs/py38/lib/python3.8/distutils/dist.py", line 966, in run_commands
	    self.run_command(cmd)
	  File "/home/matej/anaconda3/envs/py38/lib/python3.8/distutils/dist.py", line 985, in run_command
	    cmd_obj.run()
	  File "/home/matej/anaconda3/envs/py38/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
	    self.install_for_development()
	  File "/home/matej/anaconda3/envs/py38/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
	    self.run_command('build_ext')
	  File "/home/matej/anaconda3/envs/py38/lib/python3.8/distutils/cmd.py", line 313, in run_command
	    self.distribution.run_command(command)
	  File "/home/matej/anaconda3/envs/py38/lib/python3.8/distutils/dist.py", line 985, in run_command
	    cmd_obj.run()
	  File "setup.py", line 194, in run
	    self.build_extension(ext, cmake_args, build_args)
	  File "setup.py", line 233, in build_extension
	    subprocess.check_call(['cmake', '--build', '.', '--target', ext.name] + build_args, cwd=self.build_temp)
	  File "/home/matej/anaconda3/envs/py38/lib/python3.8/subprocess.py", line 364, in check_call
	    raise CalledProcessError(retcode, cmd)
	subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'core', '--config', 'Release', '--', '-j16']' returned non-zero exit status 2.
```

Previous steps (-1 to 4) in the following comment (sorry for commenting some steps, I could not undo some wrong decisions) (and sorry for indexing from -1):

**Comment by xhajnal** [comment]
```
-1 activate env
	$ python38

0 switch gcc and g++ compiler to 6 (Storm recommended setting)
	$ sudo add-apt-repository ppa:ubuntu-toolchain-r/test
	$ sudo apt-get update
	$ sudo apt install gcc-9
	$ sudo apt-get install g++-9
	$ sudo apt install gcc-6
	$ sudo apt-get install g++-6
	$ sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 7
	$ sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 7
	$ sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 6
	$ sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 6
	$ sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9
	$ sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 9
	$ sudo update-alternatives --config gcc
	# select 6
	
	$ sudo update-alternatives --config g++
	# select 6

	$ gcc --version
	gcc (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026
	$ g++ --version
	g++ (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026

1 OBTAIN PREREQUISITIES
	1.0 $ python38
	1.1 related packages
		$ sudo apt-get install build-essential git cmake libboost-all-dev libcln-dev libgmp-dev libginac-dev automake libglpk-dev libhwloc-dev libz3-dev libxerces-c-dev libeigen3-dev
		Reading package lists... Done
		Building dependency tree       
		Reading state information... Done
		automake is already the newest version (1:1.15.1-3ubuntu2).
		build-essential is already the newest version (12.4ubuntu1).
		libgmp-dev is already the newest version (2:6.1.2+dfsg-2).
		libboost-all-dev is already the newest version (1.65.1.0ubuntu1).
		libcln-dev is already the newest version (1.3.4-2).
		libeigen3-dev is already the newest version (3.3.4-4).
		libginac-dev is already the newest version (1.7.4-1).
		libglpk-dev is already the newest version (4.65-1).
		libhwloc-dev is already the newest version (1.11.9-1).
		libxerces-c-dev is already the newest version (3.2.0+debian-2).
		libz3-dev is already the newest version (4.4.1-0.3build4).
		cmake is already the newest version (3.10.2-1ubuntu2.18.04.1).
		git is already the newest version (1:2.17.1-1ubuntu0.7).
		0 upgraded, 0 newly installed, 0 to remove and 26 not upgraded.
	1.2 obtain z3
		DONE
	1.3 obtain xerces-c
		DONE
	1.3 obtain Eigen3
		TODO (skipped)
	1.4 obtain MathSAT (https://mathsat.fbk.eu/download.html)
		TODO (skipped)

2. obtain carl (http://smtrat.github.io/carl/ubuntu_1404_lts.html) with configuration for Prophesy https://moves-rwth.github.io/prophesy/installation.html
	$ git clone https://github.com/smtrat/carl.git 
	$ cd carl/
	$ git branch
	* master14
	$ mkdir build
	$ cd build/
	$ cmake .. -DUSE_CLN_NUMBERS=ON -DUSE_GINAC=ON
	-- Version: carl 14.20
	-- Using g++ 6.5.0
	-- CXX Flags:  -std=c++14 -Wunknown-pragmas -pthread -fmax-errors=5 -fdiagnostics-color=auto
	-- CXX Debug Flags: -g -O1
	-- CXX Release Flags: -O3 -DNDEBUG -O3
	-- Build type: RELEASE
	-- Building static: no
	-- cotire is disabled
	-- GMP / GMPXX 6.1.2 was found at /usr/include/x86_64-linux-gnu and /usr/lib/x86_64-linux-gnu/libgmp.so
	-- Boost 106501 was found at /usr/include and Boost_filesystem_SHARED;Boost_system_SHARED;Boost_program_options_SHARED;Boost_regex_SHARED;Boost_unit_test_framework_SHARED
	-- Eigen3 3.3.4 was found at /usr/include/eigen3
	-- Bliss is disabled
	-- CLN 1.3.6 was found at /usr/local/include and /usr/local/lib/libcln.so
	-- CoCoA is disabled
	-- GiNaC 1.7.4 was found at /usr/include/ginac and /usr/lib/libginac.so
	-- GTest 1.8.0 was found at /home/matej/Git/carl/build/resources/src/GTest-EP/googletest/include and /home/matej/Git/carl/build/resources/src/GTest-EP-build/googlemock/gtest/libgtest_main.a
	-- Doxygen was not found.
	-- Found clang-tidy, use "make tidy" to run it.
	-- Did not find clang-format, target format is disabled.
	-- Found PythonInterp: /home/matej/anaconda3/envs/py38/bin/python3 (found version "3.8.5") 
	-- Registered with cmake
	-- Run "make .travis.yml" to rebuild the travis file.
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /home/matej/Git/carl/build


	$ make lib_carl
	[  0%] Built target resources
	[100%] Built target lib_carl

	$ make -j 16

	Very long output some, things went wrong but test (see below passed)

	$ make test -j 16
	100% tests passed, 0 tests failed out of 8

	$ make doc
	make: *** No rule to make target 'doc'.  Stop.

	PROBABLY DONE


# NOW OBSOLETE (wrong branch)
# 2. Obtain carl-parser (https://github.com/ths-rwth/carl-parser)
# 	2.0 install Carl
# 	DONE tests passed 8/8
# 	$ git clone https://github.com/smtrat/carl-parser.git
# 	$ cd carl-parser
# 	$ git branch
# 	* master
# 	$ mkdir build && cd build
# 	$ cmake ..
# 		-- Use shipped jar file of ANTLR 4.7.2
# 		CMake Error at resources/antlr4.cmake:3 (message):
# 		  Can not build ANTLR4, missing binary for maven
# 		Call Stack (most recent call first):
# 		  CMakeLists.txt:66 (include)
# 
# 
# 		CMake Warning at resources/antlr4.cmake:8 (message):
# 		  Building ANTLR4 C++ runtime will probably fail, could not find uuid.h
# 		Call Stack (most recent call first):
# 		  CMakeLists.txt:66 (include)
# 
# 	2.1 obtain maven (https://linuxize.com/post/how-to-install-apache-maven-on-ubuntu-18-04/)
# 		$ sudo apt update
# 		$ sudo apt install maven
# 		$ mvn -version
# 		DONE - back to 2.
# 
# 	$ cmake ..
# 	CMake Warning at resources/antlr4.cmake:8 (message):
# 		Building ANTLR4 C++ runtime will probably fail, could not find uuid.h
# 	Call Stack (most recent call first):
# 		CMakeLists.txt:66 (include)
# 
# 	$ sudo apt-get install uuid-dev
# 	$ cmake ..
# 	DONE
# 
# 	$ make -j 16 
# 	long output, some warnings appeared
# 
# 	[ 91%] Building CXX object src/CMakeFiles/carl-parser.dir/generated/carl-parser/smtlibBaseListener.cpp.o
# 	In file included from /home/matej/Git/carl-parser/src/carl-parser/Parser.cpp:4:0:
# 	/home/matej/Git/carl-parser/src/carl-parser/Parser.h:8:10: fatal error: carl/formula/Formula.h: No such file or directory
# 	 #include <carl/formula/Formula.h>
# 	          ^~~~~~~~~~~~~~~~~~~~~~~~
# 	compilation terminated.
# 	src/CMakeFiles/carl-parser.dir/build.make:137: recipe for target 'src/CMakeFiles/carl-parser.dir/carl-parser/Parser.cpp.o' failed
# 	make[2]: *** [src/CMakeFiles/carl-parser.dir/carl-parser/Parser.cpp.o] Error 1
# 	make[2]: *** Waiting for unfinished jobs....
# 	In file included from /home/matej/Git/carl-parser/src/carl-parser/ParseTreeVisitor.cpp:1:0:
# 	/home/matej/Git/carl-parser/src/carl-parser/ParseTreeVisitor.h:6:10: fatal error: carl/core/MultivariatePolynomial.h: No such file or directory
# 	 #include <carl/core/MultivariatePolynomial.h>
# 	          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 	compilation terminated.
# 	src/CMakeFiles/carl-parser.dir/build.make:124: recipe for target 'src/CMakeFiles/carl-parser.dir/carl-parser/ParseTreeVisitor.cpp.o' failed
# 	make[2]: *** [src/CMakeFiles/carl-parser.dir/carl-parser/ParseTreeVisitor.cpp.o] Error 1
# 	CMakeFiles/Makefile2:192: recipe for target 'src/CMakeFiles/carl-parser.dir/all' failed
# 	make[1]: *** [src/CMakeFiles/carl-parser.dir/all] Error 2
# 	Makefile:114: recipe for target 'all' failed
# 	make: *** [all] Error 2
# 
# 	$ cd ..
# 	$ rm -rf build
# 	$ mkdir build && cd build && cmake .. && make
# 
# 	[ 48%] Building CXX object src/CMakeFiles/carl-parser.dir/carl-parser/ParseTreeVisitor.cpp.o
# 	In file included from /home/matej/Git/carl-parser/src/carl-parser/ParseTreeVisitor.cpp:1:0:
# 	/home/matej/Git/carl-parser/src/carl-parser/ParseTreeVisitor.h:6:10: fatal error: carl/core/MultivariatePolynomial.h: No such file or directory
# 	 #include <carl/core/MultivariatePolynomial.h>
# 	          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 	compilation terminated.
# 	src/CMakeFiles/carl-parser.dir/build.make:124: recipe for target 'src/CMakeFiles/carl-parser.dir/carl-parser/ParseTreeVisitor.cpp.o' failed
# 	make[2]: *** [src/CMakeFiles/carl-parser.dir/carl-parser/ParseTreeVisitor.cpp.o] Error 1
# 	CMakeFiles/Makefile2:192: recipe for target 'src/CMakeFiles/carl-parser.dir/all' failed
# 	make[1]: *** [src/CMakeFiles/carl-parser.dir/all] Error 2
# 	Makefile:114: recipe for target 'all' failed
# 	make: *** [all] Error 2
# 
# 
# 	2.2 Installing new cmake 3.18 -> 3.19
# 	# Same error
# 
# 	2.3 add carl to the path
# 	$ sublime ~/.bashrc
# 	export PATH="/home/matej/Git/carl/src:$PATH"
# 	export PATH="/home/matej/Git/carl/bin:$PATH"
# 	export PATH="/home/matej/Git/carl/:$PATH"
# 
# 	$ mkdir build && cd build && cmake .. && make -j 16
# 	$ make test 
# 	PASSED 8/8
# 
# 	As this is master and we need master14
# 	zip this to carl-parser_master.zip


3. Obtain carl-parser master14 (https://github.com/ths-rwth/carl-parser)
	$ git clone -b master14 https://github.com/ths-rwth/carl-parser.git
	$ cd carl-parser
	$ git branch
	* master14
	$ mkdir build && cd build
	$ cmake ..
	-- The C compiler identification is GNU 6.5.0
	-- The CXX compiler identification is GNU 6.5.0
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Check for working C compiler: /usr/bin/cc - skipped
	-- Detecting C compile features
	-- Detecting C compile features - done
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Check for working CXX compiler: /usr/bin/c++ - skipped
	-- Detecting CXX compile features
	-- Detecting CXX compile features - done
	-- Using g++ 6.5.0
	-- Using carl 14.20 from /home/matej/Git/carl/build/libcarl.so.14.20.
	-- Use shipped jar file of ANTLR 4.7.2
	-- Found Java: /usr/bin/java (found version "11.0.9") found components: Runtime 
	-- Registered with cmake
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /home/matej/Git/carl-parser/build

	$ make -j 16
	DONE


4. obtain pycarl
	$ git clone https://github.com/moves-rwth/pycarl
	$ cd pycarl
	$ python setup.py develop
	CMakeFiles/Makefile2:292: recipe for target 'CMakeFiles/parse.dir/all' failed
	make[2]: *** [CMakeFiles/parse.dir/all] Error 2
	CMakeFiles/Makefile2:299: recipe for target 'CMakeFiles/parse.dir/rule' failed
	make[1]: *** [CMakeFiles/parse.dir/rule] Error 2
	Makefile:215: recipe for target 'parse' failed
	make: *** [parse] Error 2
	Traceback (most recent call last):
	  File "setup.py", line 185, in <module>
	    setup(
	  File "/home/matej/anaconda3/envs/py38/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
	    return distutils.core.setup(**attrs)
	  File "/home/matej/anaconda3/envs/py38/lib/python3.8/distutils/core.py", line 148, in setup
	    dist.run_commands()
	  File "/home/matej/anaconda3/envs/py38/lib/python3.8/distutils/dist.py", line 966, in run_commands
	    self.run_command(cmd)
	  File "/home/matej/anaconda3/envs/py38/lib/python3.8/distutils/dist.py", line 985, in run_command
	    cmd_obj.run()
	  File "/home/matej/anaconda3/envs/py38/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
	    self.install_for_development()
	  File "/home/matej/anaconda3/envs/py38/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
	    self.run_command('build_ext')
	  File "/home/matej/anaconda3/envs/py38/lib/python3.8/distutils/cmd.py", line 313, in run_command
	    self.distribution.run_command(command)
	  File "/home/matej/anaconda3/envs/py38/lib/python3.8/distutils/dist.py", line 985, in run_command
	    cmd_obj.run()
	  File "setup.py", line 146, in run
	    self.build_extension(ext, cmake_args, build_args)
	  File "setup.py", line 182, in build_extension
	    subprocess.check_call(['cmake', '--build', '.', '--target', ext.name] + build_args, cwd=self.build_temp)
	  File "/home/matej/anaconda3/envs/py38/lib/python3.8/subprocess.py", line 364, in check_call
	    raise CalledProcessError(retcode, cmd)
	subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'parse', '--config', 'Release', '--', '-j16']' returned non-zero exit status 2.

	## AFTER I installed carl master14 and carl-parser master14
	$ python setup.py develop

	running develop
	running egg_info
	writing lib/pycarl.egg-info/PKG-INFO
	writing dependency_links to lib/pycarl.egg-info/dependency_links.txt
	writing top-level names to lib/pycarl.egg-info/top_level.txt
	reading manifest file 'lib/pycarl.egg-info/SOURCES.txt'
	reading manifest template 'MANIFEST.in'
	writing manifest file 'lib/pycarl.egg-info/SOURCES.txt'
	running build_ext
	Pycarl - Using carl with master14 branch.
	Pycarl - Using carl 14.20 from /home/matej/Git/carl/build
	Pycarl - carl parser extension from  included.
	Pycarl - Warning: No support for CLN!
	Pycarl - CMake args=['-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/matej/Git/pycarl/lib/pycarl/', '-DPYTHON_EXECUTABLE=/home/matej/anaconda3/envs/py38/bin/python3', '-DCMAKE_BUILD_TYPE=Release', '-Dcarl_DIR=/home/matej/Git/carl/build']
	-- pybind11 v2.2.dev0
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /home/matej/Git/pycarl/build/temp.linux-x86_64-3.8
	[ 20%] Linking CXX shared module ../../lib/pycarl/core.cpython-38-x86_64-linux-gnu.so
	[100%] Built target core
	Pycarl - CLN bindings skipped
	Pycarl - CMake args=['-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/matej/Git/pycarl/lib/pycarl/gmp', '-DPYTHON_EXECUTABLE=/home/matej/anaconda3/envs/py38/bin/python3', '-DCMAKE_BUILD_TYPE=Release', '-Dcarl_DIR=/home/matej/Git/carl/build']
	-- pybind11 v2.2.dev0
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /home/matej/Git/pycarl/build/temp.linux-x86_64-3.8
	[  9%] Linking CXX shared module ../../lib/pycarl/gmp/gmp.cpython-38-x86_64-linux-gnu.so
	[100%] Built target gmp
	Pycarl - CMake args=['-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/matej/Git/pycarl/lib/pycarl/formula', '-DPYTHON_EXECUTABLE=/home/matej/anaconda3/envs/py38/bin/python3', '-DCMAKE_BUILD_TYPE=Release', '-Dcarl_DIR=/home/matej/Git/carl/build']
	-- pybind11 v2.2.dev0
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /home/matej/Git/pycarl/build/temp.linux-x86_64-3.8
	[ 25%] Linking CXX shared module ../../lib/pycarl/formula/formula.cpython-38-x86_64-linux-gnu.so
	[100%] Built target formula
	Pycarl - CLN bindings skipped
	Pycarl - CMake args=['-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/matej/Git/pycarl/lib/pycarl/gmp/formula', '-DPYTHON_EXECUTABLE=/home/matej/anaconda3/envs/py38/bin/python3', '-DCMAKE_BUILD_TYPE=Release', '-Dcarl_DIR=/home/matej/Git/carl/build']
	-- pybind11 v2.2.dev0
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /home/matej/Git/pycarl/build/temp.linux-x86_64-3.8
	[ 25%] Linking CXX shared module ../../lib/pycarl/gmp/formula/formula.cpython-38-x86_64-linux-gnu.so
	[100%] Built target formula-gmp
	Pycarl - CMake args=['-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/matej/Git/pycarl/lib/pycarl/parse', '-DPYTHON_EXECUTABLE=/home/matej/anaconda3/envs/py38/bin/python3', '-DCMAKE_BUILD_TYPE=Release', '-Dcarl_DIR=/home/matej/Git/carl/build']
	-- pybind11 v2.2.dev0
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /home/matej/Git/pycarl/build/temp.linux-x86_64-3.8
	Scanning dependencies of target parse
	[ 50%] Building CXX object CMakeFiles/parse.dir/src/mod_parse.cpp.o
	[100%] Linking CXX shared module ../../lib/pycarl/parse/parse.cpython-38-x86_64-linux-gnu.so
	[100%] Built target parse
	Pycarl - CMake args=['-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/matej/Git/pycarl/lib/pycarl/gmp/parse', '-DPYTHON_EXECUTABLE=/home/matej/anaconda3/envs/py38/bin/python3', '-DCMAKE_BUILD_TYPE=Release', '-Dcarl_DIR=/home/matej/Git/carl/build']
	-- pybind11 v2.2.dev0
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /home/matej/Git/pycarl/build/temp.linux-x86_64-3.8
	Scanning dependencies of target parse-gmp
	[ 33%] Building CXX object CMakeFiles/parse-gmp.dir/src/mod_typed_parse.cpp.o
	[ 66%] Building CXX object CMakeFiles/parse-gmp.dir/src/typed_parse/parser.cpp.o
	[100%] Linking CXX shared module ../../lib/pycarl/gmp/parse/parse.cpython-38-x86_64-linux-gnu.so
	[100%] Built target parse-gmp
	Pycarl - CLN bindings skipped
	Creating /home/matej/anaconda3/envs/py38/lib/python3.8/site-packages/pycarl.egg-link (link to lib)
	pycarl 2.0.4 is already the active version in easy-install.pth

	Installed /home/matej/Git/pycarl/lib
	Processing dependencies for pycarl==2.0.4
	Finished processing dependencies for pycarl==2.0.4


4. obtain Storm - compile (https://www.stormchecker.org/documentation/obtain-storm/dependencies.html)
	4.1 obtain Storm prerequisities
		Already done in step 1
	4.2 obtain Carl
		Already done in step 2
	PROBABLY ALREADY DONE in step 1.1
	PROBABLY NOW OBSOLETE	
	4.3 obtain Boost (https://github.com/boostorg/wiki/wiki/Getting-Started%3A-Overview)
		# probably already done
		# download boost -> Git  from (https://www.boost.org/users/history/version_1_75_0.html)
		# unzip boost
		$ cd boost
		$ ./bootstrap.sh
		Building B2 engine..

		###
		###
		### Using 'gcc' toolset.
		###
		###

		> g++ --version
		g++ (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026
		Copyright (C) 2017 Free Software Foundation, Inc.
		This is free software; see the source for copying conditions.  There is NO
		warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


		###
		###

		> g++ -x c++ -std=c++11 -O2 -s -DNDEBUG builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp filesys.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathsys.cpp regexp.cpp rules.cpp scan.cpp search.cpp jam_strings.cpp startup.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp execunix.cpp fileunix.cpp pathunix.cpp -o b2
		debugger.cpp: In function ‘LIST* debug_list_read(FILE*)’:
		debugger.cpp:165:29: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
		     fscanf( in, "%d", &len );
		                             ^
		> cp b2 bjam
		tools/build/src/engine/b2
		Detecting Python version... 3.8
		Detecting Python root... /home/matej/anaconda3/envs/py38
		Unicode/ICU support for Boost.Regex?... /usr
		Generating B2 configuration in project-config.jam for gcc...

		Bootstrapping is done. To build, run:

		    ./b2
		    
		To generate header files, run:

		    ./b2 headers

		To adjust configuration, edit 'project-config.jam'.
		Further information:

		   - Command line help:
		     ./b2 --help
		     
		   - Getting started guide: 
		     http://www.boost.org/more/getting_started/unix-variants.html
		     
		   - B2 documentation:
		     http://www.boost.org/build/

		$ ./b2
		VERY LONG OUTPUT with plenty of warnings
		DONE
	4.4 build Storm
		$ git clone -b stable https://github.com/moves-rwth/storm.git
		$ cd storm
		$ git branch
		* stable
		$ mkdir build && cd build
		$ cmake ..
		-- The CXX compiler identification is GNU 6.5.0
		-- The C compiler identification is GNU 6.5.0
		-- Detecting CXX compiler ABI info
		-- Detecting CXX compiler ABI info - done
		-- Check for working CXX compiler: /usr/bin/c++ - skipped
		-- Detecting CXX compile features
		-- Detecting CXX compile features - done
		-- Detecting C compiler ABI info
		-- Detecting C compiler ABI info - done
		-- Check for working C compiler: /usr/bin/cc - skipped
		-- Detecting C compile features
		-- Detecting C compile features - done
		-- Storm - CMake install dir: /usr/local/lib/CMake/storm
		-- Storm - Building RELEASE version.
		-- Storm - Could not find ccache.
		-- Storm - Detected operating system Linux.
		-- Storm - Assuming extension for shared libraries: .so
		-- Storm - Assuming extension for static libraries: .a
		-- Storm - Build static libraries.
		-- Storm - Enabling link-time optimizations.
		-- Performing Test COMPILER_C_WORKS
		-- Performing Test COMPILER_C_WORKS - Success
		-- Performing Test COMPILER_CXX_WORKS
		-- Performing Test COMPILER_CXX_WORKS - Success
		-- Storm - Using compiler configuration gcc 6.5.0.
		-- Storm - Including Eigen 3.3.7.
		-- Storm - Using boost 106501 (library version 1_65_1).
		-- Storm - Including ExprTk.
		-- Storm - Including Sparsepp.
		-- Storm - Including ModernJSON.
		-- Storm - Linking with Z3 (version 4.4.1). (Z3 version does not support optimization)
		-- Storm - Using system version of glpk.
		-- Storm - Linking with glpk 4.65
		-- Storm - Linking with CUDD 3.0.0.
		-- Storm - Found carl using master14 branch.
		-- Storm - Use system version of carl.
		-- Storm - Linking with preinstalled carl 14.20 (include: /home/matej/Git/carl/src, library lib_carl, CARL_USE_CLN_NUMBERS: ON, CARL_USE_GINAC: ON).
		-- Storm - Use system version of xerces.
		-- Storm (GSPN) - Linking with Xerces-c 3.2.0: /usr/lib/x86_64-linux-gnu/libxerces-c.so
		-- Storm - Using shipped version of sylvan.
		-- Storm - Linking with sylvan.
		-- Storm - Linking with hwloc .
		-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
		-- Storm - Version is 1.6.4 (dev) (version 1.6.3 + 1 commits), building from git: 41ae9d56244308529f43bc9759f023e9c5d49433 (dirty: DirtyState::Clean).
		-- Registered with cmake
		-- Configuring done
		-- Generating done
		-- Build files have been written to: /home/matej/Git/storm/build
		
		$ make -j 16
		$ sublime ~/.bashrc
		# add this line
		# export PATH=$PATH:$STORM_DIR/build/bin
		$ make check
		PASSED 24/24
		$ storm --version
		Storm 1.6.4 (dev)

		DONE
```

**Comment by volkm** [comment]
Hi Matej,

you are using the stable branch of Storm which corresponds to release 1.6.3. For stormpy, you need to use the same release version to be compatible. If you use stormpy 1.6.3 instead of 1.6.0, it should work.

Best
Matthias

**Comment by xhajnal** [comment]
Hi Matthias, 

My bad, I should learn how to read.

**Comment by volkm** [comment]
No problem ;). Getting all dependencies for Prophesy is unfortunately quite complex.

If something is not understandable or unclear in the documentation, let us know. We are happy to improve the guide.

**Comment by xhajnal** [comment]
Thanks a lot.

In

> Release version: You use the latest release of Storm or the stable branch or you installed Storm via Homebrew. In these cases, you need to use the latest release of stormpy. For example, Storm 1.6.0 is compatible with stormpy 1.6.0.

I just wrongly assumed that stable version of Storm is 1.6.0 but it was just an example.
